[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pudu-ui"
version = "0.2.4"
authors = [
  { name="Jesus Henriquez" },
]
description = "UI library for Python based in pyglet"
readme = "README.md"
dependencies = [
    "psutil>=7.2.2",
    "pyglet>=3.0.dev3",
]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: User Interfaces",
]
license = "MIT"

[project.urls]
Homepage = "https://github.com/sombra-studio/pudu-ui"
Issues = "https://github.com/sombra-studio/pudu-ui/issues"

[project.optional-dependencies]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings[python]>=0.27.0",
    "mike>=2.1.0",
]

[dependency-groups]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
    "mkdocstrings[python]>=0.27.0",
    "mike>=2.1.0",
]

[tool.setuptools.packages.find]
include = ["pudu_ui*"]
exclude = ["tests*", "examples*"]

[tool.setuptools.package-data]
"pudu_ui.shaders" = ["*"]
"pudu_ui.images" = ["*"]
